### ISSUE TITLE
how to enable live reload 

### ISSUE THREAD

**Issue by bobwatcherx** [nickpeck/left#7]
in flet docs i see code like this

appp(main,view=AppView.WEB_BROWSER,port=5050)

how to implement in you framework

**Comment by nickpeck** [comment]
LeftApp() launches the app - you use the flet_mode option to control how its deployed:

import flet as ft

```
LeftApp(
    ...
    flet_mode=ft.AppView.WEB_BROWSER)
```

Another way to control this (which I typically end up using as its more flexible), is to launch my program using the flet command line options.

```
# web, live reload, port 5000
flet -w -r -p 5000

# desktop, reload
flet -r
```

**Comment by bobwatcherx** [comment]
ok thx
