### ISSUE TITLE
the state in the UI is not updated but when printed it is updated

### ISSUE THREAD

**Issue by bobwatcherx** [nickpeck/left#8]
I have another problem. For example, I want to make a counter in the yard. if I click the value will increment . I checked on print the value increased but in the application it wasn't updated. I remember in the flyer there was a name page.update() .
but what about in your framework

![Screenshot 2024-10-22 143925](https://github.com/user-attachments/assets/aaf794ba-5417-4eac-8096-314d278a4859)

here my sample code

home.py

`from flet import *
from left import LeftView
from left.helpers import redirect

from state.global_state import global_state  # Import global state

class HomeView(LeftView):
    @property
    def appbar(self):
        return AppBar(
            title=Text("left sample"),
            bgcolor="blue",
            actions=[
                ElevatedButton("Home", on_click=lambda _: redirect("/")),
                ElevatedButton("Page2", on_click=lambda _: redirect("/details/myparams"))
            ]
        )

    def add(self):
        current_counter = global_state.get_state()['counter']
        new_counter = current_counter + 1
        print(new_counter)
        global_state.update_state(counter=15, message=f"New Counter: {new_counter}")

    @property
    def controls(self):
        return [
            Text(global_state.get_state()["message"]),
            Row([
                ElevatedButton("Add", on_click=lambda _: self.add()),  # Call the add method
                Text(str(global_state.get_state().get("counter", 0))),  # Get and display the counter
            ])
        ]
`

global_state.py

`class GlobalState:
    def __init__(self):
        self.state = {
        "message": "test one",
        "name":"jon",
        "counter":12
        }

    def update_state(self, **state):
        self.state.update(state)

    def get_state(self):
        return self.state

global_state = GlobalState()
`

home_controller.py

`from left import LeftController
from state.global_state import global_state
from views.home import HomeView

class Home_controller(LeftController):
    def index(self):
        view = HomeView() 
        self._mount_view(view)
        global_state.update_state(message="Welcome to the app!")  

    def details_page(self, uid):
        view = HomeView()  
        self._mount_view(view)
        global_state.update_state(message=f" Details page you params is = {uid} ")  # Update the global state

`

**Comment by nickpeck** [comment]
The way I have used it, state would need to be a property of the view for the bindings to take place (at least, this is my preference in terms of better encapsulation - somewhat inspired by React components).

A simple example would be:

```
from flet import *
from left import LeftView
from left import LeftController, LeftApp

class HomeView(LeftView):

    def __init__(self):
        self.state = {
            "message": "test one",
            "name": "jon",
            "counter": 12
        }

    def update_state(self, **new_state):
        self.state.update(new_state)

    def add(self):
        current_counter = self.state['counter']
        new_counter = current_counter + 1
        print(new_counter)
        self.update_state(counter=new_counter, message=f"New Counter: {new_counter}")

    @property
    def controls(self):
        return [
            Text(self.state["message"]),
            Row([
                ElevatedButton("Add", on_click=lambda _: self.add()),  # Call the add method
                Text(str(self.state.get("counter", 0))),  # Get and display the counter
            ])
        ]

class Home_controller(LeftController):

    def index(self):
        view = HomeView()
        self._mount_view(view)
        view.update_state(message="Welcome to the app!")

def router(page, parts):
    Home_controller(page).index()

LeftApp(router_func=router)

```

**Comment by bobwatcherx** [comment]
ok thx
